# PyTorch Fundamentals

In [164]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.version)

<module 'torch.version' from 'e:\\conda\\envs\\cuda_test\\Lib\\site-packages\\torch\\version.py'>


### Types Of Tensors

In [204]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [205]:
scalar.ndim

0

In [206]:
# Get tensor back as python int
scalar.item()

7

In [207]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [208]:
vector.ndim

1

In [209]:
vector.shape

torch.Size([2])

In [210]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [211]:
MATRIX.ndim

2

In [212]:
MATRIX[1]

tensor([ 9, 10])

In [213]:
MATRIX.shape

torch.Size([2, 2])

In [214]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]
                      ]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [215]:
TENSOR.ndim

3

In [216]:
TENSOR.shape

torch.Size([1, 3, 3])

In [217]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

### Random Tensors

In [179]:
# Create a random tensors of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.9984, 0.9203, 0.2416, 0.5610],
         [0.0827, 0.5029, 0.6594, 0.8929],
         [0.3681, 0.3067, 0.4743, 0.6818]]])

In [180]:
random_tensor.ndim

3

In [181]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [182]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [183]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [184]:
ones.dtype

torch.float32

In [185]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [186]:
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [187]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [188]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [189]:
float_32_tensor.dtype

torch.float32

In [190]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [191]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors attribute

In [192]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5130, 0.4957, 0.9321, 0.8264],
        [0.9553, 0.8412, 0.1079, 0.3562],
        [0.2100, 0.4870, 0.6199, 0.2350]])

In [193]:
# Find out details about it
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5130, 0.4957, 0.9321, 0.8264],
        [0.9553, 0.8412, 0.1079, 0.3562],
        [0.2100, 0.4870, 0.6199, 0.2350]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [194]:
# Create a tensor and add 10 to it
tensor =  torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [195]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [196]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [197]:
# Try out pyTorch inbuild functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [198]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

In [199]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [200]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [201]:
%%time
value = 0
for i in range(len(tensor)):
    value +=tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 8.52 ms


In [202]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 1 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [203]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B)  torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the sahape of one of our tensors using transpose


In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner  dimesions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1, 100 ,10)
x

In [ ]:
torch.min(x), x.min()

In [ ]:
torch.max(x), x.max()

In [ ]:
# find the mean- torch.mean() requires float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

## Finding the positional min and max of tensor

In [ ]:
x

In [ ]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target value occured
x.argmin()

In [ ]:
x[0]

In [ ]:
# find the position in tensor that has maximum value with argmax()
x.argmax()

In [ ]:
x[9]

## Reshaping Stacking, Squeezing and unsqueezing tensors

In [ ]:
# Let's Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

In [ ]:
# changing z changes x (because of veiw of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x] ,dim=0)
x_stacked

In [ ]:
# Squeezing tensor
torch.squeeze(x_reshaped)

In [ ]:
# Unsqueezing tensor
torch.unsqueeze(x, dim=0)

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,24,3)) # [height, width, color_channels]

# Permute the original tesor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 ,1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, widht]

In [ ]:
x_original[0, 0, 0] = 23142
x_original[0,0,0], x_permuted[0,0,0]

## Indexing (Selecting data from tensors)

In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

In [ ]:
# Let's index on our new tensor
x[0]

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0,0]

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0,2,2]

In [ ]:
# You cna als use ":" to select all of target dimesion
x[:,0]

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 and 2nd dimesion
x[:, :, 1]

In [ ]:
# Get  all values of 0 dimension but only 1 index value of 1st and 2nd dimesion
x[:, 1, 1]

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimesion
x[0,0,:]

In [ ]:
# index on x to return 9
print(x[:,2,2])
# index on x to return 3,6,9
x[:, :, 2]

## PyTorch tensors & NumPy

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning when converting from numpy to torch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

In [ ]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
# Change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

## Reproducebility (trying to take random out of random)

To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**

In [ ]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.1640, 0.8384, 0.1902, 0.8783],
        [0.6330, 0.0339, 0.1279, 0.2027],
        [0.8697, 0.0212, 0.8455, 0.6838]])
tensor([[0.7263, 0.7342, 0.6653, 0.8842],
        [0.4929, 0.0752, 0.4939, 0.7821],
        [0.7944, 0.2126, 0.6406, 0.1132]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 124
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.1526, 0.6311, 0.8407, 0.4741],
        [0.5123, 0.1231, 0.3097, 0.4665],
        [0.4847, 0.2217, 0.1413, 0.4469]])
tensor([[0.1526, 0.6311, 0.8407, 0.4741],
        [0.5123, 0.1231, 0.3097, 0.4665],
        [0.4847, 0.2217, 0.1413, 0.4469]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html 
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

In [ ]:
!nvidia-smi

Fri Jul 26 01:24:15 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti   WDDM  |   00000000:2D:00.0  On |                  N/A |
|  0%   49C    P8             20W /  240W |    1318MiB /   8192MiB |     11%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
### Check the GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device  = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of device
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensor back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix the gpu tensor with numpy issue, we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')